name: CI

on:
  pull_request:
    branches:
      - master
      - feature/*

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: yarn

      - run: yarn run lint

  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: yarn

      - name: Set git credentials for test
        run: git config --global user.name “John Smith”

      - run: yarn run test
