const args = [
	{
		name: "path-prefix",
		options: {
			type: String,
			alias: "path",
			desc:
				"path to prefix to add to all files paths generated by the generator",
			required: false
		}
	}
];

const generateArgs = generator => {
	for (arg of args) {
		generator.argument(arg.name, arg.options);
	}
};

module.exports = { generateArgs, args };
